# Generated by Django 5.1.5 on 2025-01-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlSafeName', models.TextField(unique=True)),
                ('displayName', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlSafeTitle', models.TextField(unique=True)),
                ('urlMediaType', models.TextField()),
                ('displayTitle', models.TextField(blank=True, db_index=True, null=True)),
                ('tropes', models.ManyToManyField(related_name='medias', to='core.trope')),
            ],
        ),
    ]
