# Generated by Django 5.1.5 on 2025-02-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_trope_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='urlSafeTitle',
            field=models.TextField(),
        ),
    ]
