# Generated by Django 5.1.5 on 2025-02-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_media_urlsafetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='displayIsDefinitive',
            field=models.BooleanField(default=False),
        ),
    ]
