const mediaCategories: [string, string][] = [
  ["Advertising", "Advertisement"],
  ["Animation", "Animation"],
  ["Anime", "Anime"],
  ["ARG", "ARG"],
  ["Art", "Art"],
  ["AudioPlay", "Audio Play"],
  ["Blog", "Blog"],
  ["ComicBook", "Comic Book"],
  ["ComicStrip", "Comic Strip"],
  ["Fanfic", "Fanfic"],
  ["Franchise", "Franchise"],
  ["Film", "Film"],
  ["LetsPlay", "Let's Play"],
  ["Literature", "Literature"],
  ["Magazine", "Magazine"],
  ["Main", "Main"],
  ["Manga", "Manga"],
  ["Manhua", "Manhua"],
  ["Manhwa", "Manhwa"],
  ["Music", "Music"],
  ["Myth", "Myth"],
  ["Platform", "Platform"],
  ["Podcast", "Podcast"],
  ["Radio", "Radio"],
  ["Ride", "Ride"],
  ["Roleplay", "Roleplay"],
  ["Series", "TV Series"],
  ["TabletopGame", "Tabletop Game"],
  ["Theatre", "Theater"],
  ["Toys", "Toys"],
  ["VideoGame", "Video Game"],
  ["VisualNovel", "Visual Novel"],
  ["WebAnimation", "Web Animation"],
  ["Webcomic", "Webcomic"],
  ["WebOriginal", "Web Original"],
  ["Website", "Website"],
  ["WebVideo", "Web Video"],
  ["WesternAnimation", "Western Animation"],
  ["Wrestling", "Wrestling"],
];

export default mediaCategories;
